name: "Test ENVs"

on:
  push:

env:
  HALLO: world
  
 
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      -  run: |
          $GITHUB_ENV << EOF
          WORLD=$HALLO
          EOF
          
      -  run: |
          echo "Hello $WORLD"

