name: "Test ENVs"

on:
  push:

env:
  HALLO: World
  
 
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      -  run: |
          echo "WORLD=$HALLO" >> $GITHUB_ENV
          
      -  run: |
          echo "Hello $WORLD"

